// Those books names should match with https://content-finder.herokuapp.com/BooksAvaliable
// This enpoint is returning books names with _ instead of space but this is fixed in GET route

const books = [
  {
    bookName: 'American Government',
    fileName: 'us-government-baked.xhtml',
    baked: true,
    contentFetchedAt: '16.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Anatomy & Physiology',
    fileName: 'anatomy-physiology-raw.xhtml',
    baked: false,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Algonquin College MAT0032',
    fileName: 'algonquin-raw.xhtml',
    baked: false,
    contentFetchedAt: '21.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Applied Finite Mathematics',
    fileName: 'applied-finite-raw.xhtml',
    baked: false,
    contentFetchedAt: '21.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Principles of Macroeconomics for AP Courses 2e',
    fileName: 'principles-macro2e-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'AP Physics',
    fileName: 'college-physics-ap-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Astronomy',
    fileName: 'astronomy-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Biology',
    fileName: 'biology-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Biology for AP Courses',
    fileName: 'apbiology-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Biology 2e',
    fileName: 'biology2e-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Business Ethics',
    fileName: 'business-ethics-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Calculus Volume 1',
    fileName: 'calculus-vol1-raw.xhtml',
    baked: false,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Chemistry',
    fileName: 'chemistry-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Collaborative Statistics Modified by T Short',
    fileName: 'collaborative-statistics-tshort-raw.xhtml',
    baked: false,
    contentFetchedAt: '21.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Collaborative Statistics with edits Teegarden',
    fileName: 'collaborative-statistics-teegarden-raw.xhtml',
    baked: false,
    contentFetchedAt: '21.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'College Algebra',
    fileName: 'college-algebra-raw.xhtml',
    baked: false,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'College Physics',
    fileName: 'college-physics-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Concepts of Biology',
    fileName: 'concepts-biology-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Elementary Algebra',
    fileName: 'elementary-algebra-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'English Home Language Grade 5',
    fileName: 'english-home-language-raw.xhtml',
    baked: false,
    contentFetchedAt: '21.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Human Anatomy',
    fileName: 'human-anatomy-raw.xhtml',
    baked: false,
    contentFetchedAt: '21.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'KSU TM College Physics I',
    fileName: 'ksu-tm-college-raw.xhtml',
    baked: false,
    contentFetchedAt: '21.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Microbiology',
    fileName: 'microbiology-raw.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Intermediate Algebra',
    fileName: 'intro-algebra-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Introductory Statistics',
    fileName: 'intro-stats-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Introduction to Business',
    fileName: 'intro-business-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Introductory Business Statistics',
    fileName: 'intro-business-stats-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Prealgebra',
    fileName: 'prealgebra-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Principles of Economics 2e',
    fileName: 'principles-economics2e-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Project Management',
    fileName: 'project-managment-raw.xhtml',
    baked: false,
    contentFetchedAt: '21.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Psychology',
    fileName: 'psychology-raw.xhtml',
    baked: false,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Fizyka dla szkol wyzszych Tom 1',
    fileName: 'katalyst-physics-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Rationality',
    fileName: 'rationality-raw.xhtml',
    baked: false,
    contentFetchedAt: '21.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Sociology 2e',
    fileName: 'intro-sociology2e-raw.xhtml',
    baked: false,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'Understanding Basic Music Theory',
    fileName: 'basic-music-theory-raw.xhtml',
    baked: false,
    contentFetchedAt: '21.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'University Physics Volume 1',
    fileName: 'u-physics-baked.xhtml',
    baked: true,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },
  {
    bookName: 'US History',
    fileName: 'us-history-raw.xhtml',
    baked: false,
    contentFetchedAt: '15.11.2018',
    contentFetchedFrom: 'katalyst01.cnx.org',
  },  
]

module.exports = {
  books
}
